
const screenWidth = window.innerWidth;

export const ENEMY_WIDTH = screenWidth >= 1023 ? 50 : 40;
export const ENEMY_GAP = screenWidth >= 1023 ? 40 : 25;
export const ENEMY_HEIGHT = screenWidth >= 1023 ? 50 : 20;

const ENEMY_VELOCITY_MOBILE = 30;
const ENEMY_VELOCITY_DESKTOP = 20;
export const ENEMY_VELOCITY = screenWidth >= 1023 ? ENEMY_VELOCITY_DESKTOP : ENEMY_VELOCITY_MOBILE;

const MAX_HORIZONTAL_ENEMY_DISTANCE_MOBILE = 50;
const MAX_VERTICAL_ENEMY_DISTANCE_MOBILE = 350;

const MAX_HORIZONTAL_ENEMY_DISTANCE_DESKTOP = 300;
const MAX_VERTICAL_ENEMY_DISTANCE_DESKTOP = 550;

export const MAX_HORIZONTAL_ENEMY_DISTANCE = screenWidth >= 1023 ? MAX_HORIZONTAL_ENEMY_DISTANCE_DESKTOP : MAX_HORIZONTAL_ENEMY_DISTANCE_MOBILE;
export const MAX_VERTICAL_ENEMY_DISTANCE = screenWidth >= 1023 ? MAX_VERTICAL_ENEMY_DISTANCE_DESKTOP : MAX_VERTICAL_ENEMY_DISTANCE_MOBILE;